name: statsseminar

channels:
  - astropy

dependencies:
  - python=3
  - astropy
  - cython
  - numpy
  - matplotlib
  - scipy
  - emcee
  - pip
  - pip:
    - git+https://github.com/adrn/gala.git
    - schwimmbad
